app/models.py
from app import db
from datetime import datetime

class Teacher(db.Model):
    __tablename__ = 'teachers'
    id = db.Column(db.Integer, primary_key=True)
    is_admin = db.Column(db.Boolean, default=False)
    name = db.Column(db.String(64), index=True)
    id_card = db.Column(db.String(64), index=True, unique=True)
    race = db.Column(db.String(64))
    origin = db.Column(db.String(64))
    tel = db.Column(db.String(64))
    course = db.Column(db.String(64))
    is_header_teacher = db.Column(db.Boolean())
    working_date = db.Column(db.Date())
    create_time = db.Column(db.DateTime())
    change_time = db.Column(db.DateTime())

    @property
    def sex(self):
        return "男" if int(self.id_card[-2:-1]) % 2 else "女" 

    @property
    def birthday(self):
        return datetime.strptime(self.id_card[6:14],'%Y%m%d')

    def __repr__(self):
        return '<Teacher %r>' % self.name

app/main/forms.py
from flask import url_for
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, BooleanField, SelectField, SubmitField
from wtforms.validators import Required, Length, Regexp
from wtforms import ValidationError
from app.models import Teacher
from markupsafe import Markup

class TeacherForm(FlaskForm):
    name = StringField('姓名', validators=[Required()])
    id_card = StringField('身份证号', validators=[Required(),
        Regexp('^[1-9][0-9]{16}[0-9X]$', 0, '请输入正确身份证号，X大写')])
    race = StringField('民族', validators=[Required()])
    origin = StringField('籍贯', validators=[Required()])
    tel = StringField('手机号', validators=[Required(),
        Regexp('^1[35678][0-9]{9}$', 0, '请输入正确的手机号')])
    course = StringField('任教学科', validators=[Required()])
    is_header_teacher = SelectField('班主任', coerce=int,
            choices=[(0, "否"), (1, "是")])
    working_date = DateField('工作日期', 
            format='%Y/%m/%d', validators=[Required()])
    submit = SubmitField('保存')

class NewTeacherForm(TeacherForm):
    def validate_id_card(self, field):
        existed = Teacher.query.filter_by(id_card=field.data).first()
        if existed:
            raise ValidationError(
                    Markup('身份证已存在，查看/修改信息<a href="'
                        + url_for('main.view', id=existed.id)
                        + '">单击此处</a>'))

class TeacherChangeRequestForm(FlaskForm):
    name = StringField('姓名', validators=[Required()])
    submit = SubmitField('查看')

app/__init__.py
from config import config
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)
    db.init_app(app)

    from app.main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import views, errors

app/main/views.py
from app.main import main
from app.main.forms import TeacherForm, NewTeacherForm, TeacherChangeRequestForm
from app import db
from app.models import Teacher
from app.excel import write2excel
from flask import render_template, flash, redirect, url_for, abort, session, g
from datetime import datetime
from markupsafe import Markup

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/add', methods=['GET', 'POST'])
def add():
    form = NewTeacherForm()
    if form.validate_on_submit():
        teacher = Teacher(
                name = form.name.data,
                id_card = form.id_card.data,
                race = form.race.data,
                origin = form.origin.data,
                tel = form.tel.data,
                course = form.course.data,
                is_header_teacher = form.is_header_teacher.data,
                working_date = form.working_date.data,
                create_time = datetime.now(), 
                change_time = datetime.now())
        db.session.add(teacher)
        db.session.commit()
        flash('资料保存完毕','success')
        return redirect(url_for('main.view', id=teacher.id))
    try:
        form.name.data = session.pop('name')
    except KeyError:
        pass
    return render_template('form.html', form=form, form_header='新建')

@main.route('/view/<int:id>')
def view(id):
    current_teacher = Teacher.query.get_or_404(id)
    return render_template('view.html', teacher=current_teacher)

@main.route('/change', methods=['GET', 'POST'])
def change_request():
    form = TeacherChangeRequestForm()   
    if form.validate_on_submit():
        query_data = Teacher.query.filter_by(name=form.name.data) 
        num = query_data.count()
        if num == 1:
            id = query_data.first().id
            return redirect(url_for('main.view', id=id))
        if num > 1:
            table = [('#', '姓名', '出生日期', '任教科目', '操作')]   
            i = 1
            for data in query_data:
                name = data.name
                birthday = data.birthday.strftime('%Y年%m月')
                course = data.course
                action = Markup('<a href="'\
                    + url_for('main.change', id=data.id)\
                    + '">修改</a>')
                table.append((i, name, birthday, course, action))
                i += 1
            g.table = table
            return render_template('table.html', table_title='请选择要修改的数据')
        if num == 0:
            session['name'] = form.name.data
            flash(Markup('没有查询到您的信息，<a href="'
                +url_for('main.add')+'">点击此处</a>新建'), 'warning')
    return render_template('form.html', form=form, form_header='请输入姓名')

@main.route('/change/<int:id>', methods=['GET', 'POST'])
def change(id):
    current_teacher = Teacher.query.get_or_404(id)
    form = TeacherForm()
    if form.validate_on_submit():
        current_teacher.name = form.name.data
        current_teacher.id_card = form.id_card.data
        current_teacher.race = form.race.data
        current_teacher.origin = form.origin.data
        current_teacher.tel = form.tel.data
        current_teacher.course = form.course.data
        current_teacher.is_header_teacher = form.is_header_teacher.data
        current_teacher.working_date = form.working_date.data
        current_teacher.change_time = datetime.now()
        db.session.add(current_teacher)
        db.session.commit()
        flash('您的资料已经更新', 'success')
        return redirect(url_for('main.view',id=id))
    form.name.data = current_teacher.name
    form.id_card.data = current_teacher.id_card
    form.race.data = current_teacher.race
    form.origin.data = current_teacher.origin
    form.tel.data = current_teacher.tel
    form.course.data = current_teacher.course
    form.is_header_teacher.data = current_teacher.is_header_teacher
    form.working_date.data = current_teacher.working_date
    return render_template('form.html', form=form, form_header='修改资料')

@main.route('/del/<int:id>')
def delete(id):
    current_teacher = Teacher.query.get_or_404(id)
    name = current_teacher.name
    db.session.delete(current_teacher)
    db.session.commit()
    flash('{}的填报资料已经删除'.format(name),'danger')
    return redirect(url_for('main.index'))

@main.route('/all')
def all():
    table = [('#', '姓名', '性别', '出生日期', '民族', '身份证号',
        '籍贯','电话号码','任教科目', '班主任', '填写时间', '操作')]   
    i = 1
    for data in Teacher.query.all():
        name = data.name
        sex = data.sex
        birthday = data.birthday.strftime('%Y-%m-%d')
        race = data.race
        id_card = data.id_card
        origin = data.origin
        tel = data.tel
        course = data.course
        is_header_teacher = "是" if data.is_header_teacher else "否"
        change_time = data.change_time.strftime('%m-%d %H:%M')
        action = Markup('<a href="'\
            + url_for('main.change', id=data.id)\
            + '">修改</a>'+' | '+'<a style=\'color:red\' href="'\
            + url_for('main.delete', id=data.id)\
            + '">删除</a>')
        table.append((i, name, sex, birthday, race, id_card,
            origin, tel, course, is_header_teacher, change_time, action))
        i += 1
    g.table = table
    session['table'] = table
    return render_template('table.html', table_title='全部资料')

@main.route('/out')
def out():
    table = session.get('table')
    if table is None:
        return redirect(url_for('main.all'))
    data = (row[:-2] for row in table)
    name = '导出'
    filename = write2excel(name, data)
    return redirect(url_for('static', filename=filename, _external=True))

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}肥城三中2017级{% endblock %}

{% block navbar %}

{% endblock %}

{% block content %}
{{ utils.flashed_messages(dismissible=True) }}
<div class="container">
	{% block page_content %}
	{% endblock %}
</div>
{% endblock %}

app/templates/form.html
{% extends 'base.html' %}

{% block styles %}
{{ super() }}
	<link href="{{ url_for('static', filename='bootstrap-datetimepicker/bootstrap-datepicker3.min.css') }}" rel="stylesheet">
{% endblock %}

{% block page_content %}
<div class="page-header">
	<h1>{{ form_header }}</h1>
</div>
<div class="col-md-4">
	{{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
	<script src="{{ url_for('static', filename='bootstrap-datetimepicker/bootstrap-datepicker.min.js') }}"></script>
	<script src="{{ url_for('static', filename='bootstrap-datetimepicker/bootstrap-datepicker.zh-CN.min.js') }}" charset="UTF-8"></script>
	<script type"text/javascript">
		$('#working_date').datepicker({
			weekStart: 1,
			autoclose: 1,
			daysofWeekHighlighted: "0,6",
			format: "yyyy/mm/dd",
			language: "zh-CN"
			});
	</script>
	
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block page_content %}
<div class="page-header">
	<h1>新分教师信息采集</h1>
	<p>填报时间：2017年4月26日</p>
	<p>填报要求</p>
	<p>
		<a class="btn btn-primary" href="{{url_for('main.add')}}" role="button">新建</a>
		<a class="btn btn-default" href="{{url_for('main.change_request')}}" role="button">查看/修改</a>
	</p>
{% endblock %}

app/templates/table.html
{% extends 'base.html' %}
{% block page_content %}
<div class="page-header">
	<h1>{{ table_title }}</h1>
</div>
{% if table_title == "全部资料" %}
<div class="col-md-4">
<a class="btn btn-primary" href="{{url_for('main.out')}}" role="button">导出</a>
</div>
{% endif %}
<div class="col-md-12">
	<table class="table table-hover">
		<thead>
			<tr>
				{% for th in g.table[0] %}
					<th>{{ th }}</th>
				{% endfor %}
			</tr>
		</thead>
		<tbody>
			{% for row in g.table[1:] %}
				<tr>
					{% for cell in row %}
					<td> {{ cell }}</td>
					{% endfor %}
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}

app/templates/view.html
{% extends 'base.html' %}

{% block page_content %}
<div class="page-header">
	<h1>{{ teacher.name }}</h1>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">填报资料</h3>
	</div>
	<div class="panel-body">
		<p>
			<strong>性别：</strong>{{teacher.sex}}
		</p>
		<p>
			<strong>出生日期：</strong>{{teacher.birthday.strftime('%Y年%m月%d日')}}
		</p>
		<p>
			<strong>身份证号：</strong>{{teacher.id_card}}
		</p>
		<p>
			<strong>民族：</strong>{{teacher.race}}
		</p>
		<p>
		<strong>籍贯：</strong>{{teacher.origin}}
		</p>
		<p>
			<strong>电话：</strong>{{teacher.tel}}
		</p>
		<p>
			<strong>任教课程：</strong>{{teacher.course}}
		</p>
		<p>
			<strong>班主任：</strong>
			{% if teacher.is_header_teacher %}是{% else %}否{% endif %}
		</p>
		<p>
			<strong>参加工作时间：</strong>{{teacher.working_date.strftime('%Y年%m月%d日')}}
		</p>
		<p>
			<strong>填写时间：</strong>{{teacher.change_time.strftime('%Y年%m月%d日 %H:%M:%S')}}
		</p>
		<p>
			<a class="btn btn-primary" href="{{url_for('main.change',id=teacher.id)}}" role="button">修改</a>
			<a class="btn btn-default" href="{{url_for('main.index')}}" role="button">返回首页</a>
		</p>
	</div>
</div>
{% endblock %}